version: "2"
services:
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.http.routers.${DKTL_SLUG}-web.rule=Host(`${DKTL_PROXY_DOMAIN}`)"
      - "traefik.http.routers.${DKTL_SLUG}-web.entrypoints=web"
