version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install shunit
          command: |
            pwd
            ls -la
      - run:
          name: Run tests
          command: |
            cd tests
            ls

