version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: environment setup
          command: |
            composer --global require phpunit/phpunit
      - run:
          name: debug
          command: |
            pwd
            ls
            docker ps
            composer
