# Docker and Docker Compose based environment for Drupal.
# Combines with docker-compose.common.yml
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

# Web node
version: "2"
services:
  # CLI node
  # Used for all console commands and tools.
  cli:
    volumes:
      - "${DKTL_PROJECT_DIRECTORY}:/var/www/"
